name: Publish Docker Image
on: push

jobs:
  push_dockeer_image_to_registry:
    name: Push Docker Image to registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
