name: Publish Docker Image
on: push

jobs:
  push_dockeer_image_to_registry:
    name: Push Docker Image to registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract Metadata (Tags and Labels) for Docker Image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: kevins0004/publish-docker_image
      
          
          
